Label /usr/libexec/rpm-ostreed as rpm_exec_t. BZ(1309075)
If a user does atomic updates-testing rebase then he ends up with SELinux error:

Receiving objects: 92% (3773/4069) 859.0 kB/s 99.6 MB
error: fsetxattr: Invalid argument

It happens because /usr/libexec/rpm-ostreed is not labeled correctly.