Allow virt_qemu_ga_run_unconfined control guest-exec (bsc#1237450)
The qemu-ga guest-exec command allows a host to execute
arbitrary commands on the guest.

Before this commit, when the guest-exec command was used
with qemu-guest-agent, SELinux allowed the the host to execute
processes that were generally allowed by the virt_qemu_ga_t domain
and denied accessing processes that were not allowed.

However, this bad in security and usability as not all
commands are denied and not all commands are allowed and there
is no way to configure which ones are allowed, except by
giving the main virt_qemu_ga_t domain more permissions in general.

This breaks use cases such as ansible with the qemu-guest-agent plugin.

Quick reproducer for the problem that this commit tries to solve:
Using virsh on the host:
- list VM names and grab your guest where you want to execute commands on
- for example execute this with cloud-init installed on the guest:
```
$ qemu-agent-command <your-vm-name> '{"execute": "guest-exec", "arguments": { "path": "/usr/bin/cloud-init", "arg": [ "/" ], "capture-output": true }}'
error: guest agent command failed: unable to execute QEMU agent command 'guest-exec': Failed to execute child process “/usr/bin/cloud-init” (Permission denied)

$ qemu-agent-command <your-vm-name> '{"execute": "guest-exec", "arguments": { "path": "/usr/bin/ls", "arg": [ "/" ], "capture-output": true }}'
{"return":{"pid":109083}}
```

With this commit and a change in libvirt, this can be controlled with the
virt_qemu_ga_run_unconfined boolean.

virt_qemu_ga_run_unconfined off -> both ls and cloud-init will fail with guest-exec
virt_qemu_ga_run_unconfined on -> both ls and cloud-init will be executed with guest-exec

Requires a change with a selinux-helper in libvirt to be functional!